import { defineWorkspace } from "vitest/config"

export default defineWorkspace([
  "packages/adapters",
  "packages/agent",
  "packages/cli",
  "packages/build",
  "packages/config",
  "packages/core",
  "packages/deploy",
  "packages/devtools",
  "packages/di",
  "packages/errors",
  "packages/evals",
  "packages/lifecycle",
  "packages/logger",
  "packages/memory",
  "packages/mcp-server",
  "packages/model",
  "packages/plugin",
  "packages/runtime",
  "packages/shared",
  "packages/tools",
  "packages/tracing",
  "packages/typescript-config",
  "packages/skills",
  "packages/workflows",
  "packages/ontology",
  "packages/governance",
  "packages/security",
  "packages/observability",
  "tools/generators",
  "tests",
])
