export enum ErrorCode {
  ConfigInvalid = "VIBE_CONFIG_INVALID",
  RuntimePanic = "VIBE_RUNTIME_PANIC",
  ProviderUnavailable = "VIBE_PROVIDER_UNAVAILABLE",
  ProviderAuthFailed = "VIBE_PROVIDER_AUTH_FAILED",
  ProviderRateLimited = "VIBE_PROVIDER_RATE_LIMITED",
  ValidationFailed = "VIBE_VALIDATION_FAILED",
  ToolExecutionFailed = "VIBE_TOOL_EXECUTION_FAILED",
  Timeout = "VIBE_TIMEOUT",
  Cancelled = "VIBE_CANCELLED",
  LifecycleInvalidTransition = "VIBE_LIFECYCLE_INVALID_TRANSITION",
  PluginConflict = "VIBE_PLUGIN_CONFLICT",
  PluginNotFound = "VIBE_PLUGIN_NOT_FOUND",
  DiResolutionFailed = "VIBE_DI_RESOLUTION_FAILED",
  DiCircularDependency = "VIBE_DI_CIRCULAR_DEPENDENCY",
  NotImplemented = "VIBE_NOT_IMPLEMENTED",
  InternalError = "VIBE_INTERNAL_ERROR",
}
